title: "Karthik Rajesh"
logo: /assets/img/headshot.png
description: >-
  MSc in Business Analytics (University of Nottingham). Project Developer at
  EMtel. This portfolio showcases my machine-learning projects and professional
  experience.

theme: jekyll-theme-minimal
show_downloads: false
lang: en
timezone: Europe/London
permalink: pretty

# Site URLs
# IMPORTANT for correct links on GitHub Pages (repo is /portfolio)
url: "https://im-karthikrajesh.github.io"
baseurl: "/portfolio"

author:
  name: "Karthik Rajesh"
  email: "karthikrajesh5@gmail.com"
  github: "https://github.com/im-karthikrajesh"
  linkedin: "https://www.linkedin.com/in/karthikrajesh05"

# Build
markdown: kramdown
kramdown:
  input: GFM

# SEO & Sitemap (supported by GitHub Pages)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Tidy output & ignore local bundles
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
